services:

  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: paofu

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: youkyoku/paofu:latest
    container_name: paofu
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"

volumes:
  mysql_data:
