spring.application.name=nextapp
# DB接続(MariaDB)
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost/gips
spring.datasource.username=root
spring.datasource.password=G1ps#solid
spring.jpa.hibernate.ddl-auto=none
# MyBatis設定
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.gips.taskapp.dto
# 日付のフォーマット指定
spring.mvc.format.date=yyyy-MM-dd
