spring.application.name=nextapp

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.url=jdbc:sqlserver://khlink-srv.database.windows.net:1433;database=free-sql-db-khlink-test;encrypt=true;trustServerCertificate=false

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.gips.taskapp.dto

spring.mvc.format.date=yyyy-MM-dd